; These are the default user setting values for the Enigma suite. They are used by the Options skin to restore default values.
; You should not make changes to this file unless you know what you're doing. Instead, use Options.inc to change your active personal settings.

[Variables]

;-----------------------
; LAYOUT

DefaultStylesheet=Enigma Dark

;-----------------------
; GENERAL

DefaultNote1Path=#*@*#User\Notes\Notes.txt
DefaultNote2Path=#*@*#User\Notes\Tasks.txt
DefaultNote3Path=#*@*#User\Notes\About.txt
DefaultNoteHeight=200
DefaultDrive1=C
DefaultDrive2=E
DefaultDrive3=F
DefaultNetworkMaxDownload=1000000
DefaultNetworkMaxUpload=500000
DefaultSystemGraphType=Floating
DefaultCalendarEventFile=#*@*#User\Calendars\Holidays.xml
DefaultCalendarShowEvents=1
DefaultCalendarExtraDays=1
DefaultCalendarLeadingZeroes=0
DefaultCalendarMondays=0
DefaultGalleryPath=%USERPROFILE%\Pictures
DefaultGallerySubfolders=1
DefaultGalleryRatio=3/4
DefaultGalleryPosition=Center
DefaultVolumeIncrement=5
DefaultTriptychInterval=30
DefaultTriptychDisabled=0
DefaultProcessInterval=5

;-----------------------
; MUSIC

DefaultMusicPlayerType=3
DefaultMusicPlayer=iTunes

;-----------------------
; FEEDS

DefaultFeed1=http://news.google.com/news?pz=1&ned=us&hl=en&topic=h&num=10&output=rss
DefaultFeed2=http://rainmeter.net/forum/feed.php
DefaultFeed3=http://kaelri.com/feed/
DefaultGmailUsername=YourUsernameHere
DefaultGmailPassword=YourPasswordHere
DefaultFacebookFeed=YourFacebookFeedHere
DefaultGoogleCalendar1=YourCalendarAddressHere
DefaultGoogleCalendar2=YourCalendarAddressHere
DefaultGoogleCalendar3=YourCalendarAddressHere
DefaultGoogleCalendarWriteEvents=1
DefaultRTMusername=YourUserNameHere
DefaultRTMpassword=YourPasswordHere
DefaultRTMlist1=YourListNumberHere
DefaultRTMlist2=YourListNumberHere
DefaultRTMlist3=YourListNumberHere
DefaultTwitterUsername=YourUsernameHere
DefaultTwitterPassword=YourPasswordHere

;-----------------------
; WORLD

DefaultWeatherCode=
DefaultWeatherCodeName=YourWeatherCodeHere
DefaultWeatherCodeLat=
DefaultWeatherCodeLon=
DefaultUnit=c
DefaultWorld1WeatherCode=44418
DefaultWorld1WeatherCodeName=London
DefaultWorld1WeatherCodeLat=51.51
DefaultWorld1WeatherCodeLon=-0.13
DefaultWorld2WeatherCode=2514815
DefaultWorld2WeatherCodeName=Washington
DefaultWorld2WeatherCodeLat=38.9
DefaultWorld2WeatherCodeLon=-77.03
DefaultWorld3WeatherCode=455825
DefaultWorld3WeatherCodeName=Rio de Janeiro
DefaultWorld3WeatherCodeLat=-22.98
DefaultWorld3WeatherCodeLon=-43.2

;-----------------------
; APPS

DefaultApp1=Chrome
DefaultApp1Path=chrome.exe
DefaultApp1PathHandle=chrome.exe
DefaultApp1Label=WEB
DefaultApp1Icon=#*@*#Images\Launcher\Chrome.#*ColorImage*#.png
DefaultApp2=Notepad
DefaultApp2Path=notepad.exe
DefaultApp2PathHandle=notepad.exe
DefaultApp2Label=TEXT
DefaultApp2Icon=#*@*#Images\Launcher\Text.#*ColorImage*#.png
DefaultApp3=Explorer
DefaultApp3Path=explorer.exe
DefaultApp3PathHandle=explorer.exe
DefaultApp3Label=FILES
DefaultApp3Icon=#*@*#Images\Launcher\Start.#*ColorImage*#.png
DefaultApp4=Skype
DefaultApp4Path=C:\Program Files\Skype\Phone\skype.exe
DefaultApp4PathHandle=skype.exe
DefaultApp4Label=CHAT
DefaultApp4Icon=#*@*#Images\Launcher\Skype.#*ColorImage*#.png
DefaultApp5=Rainmeter.net
DefaultApp5Path=http://rainmeter.net/
DefaultApp5Handle=rainmeter.exe
DefaultApp5Label=FORUM
DefaultApp5Icon=#*@*#Images\Launcher\Rainmeter.png

;-----------------------
; SEARCH

DefaultSearch1=Google
DefaultSearch1Command="http://google.com/search?q=$UserInput$"
DefaultSearch1Icon=#*@*#Images\Search\Google.#*ColorImage*#.png
DefaultSearch2=Wikipedia
DefaultSearch2Command="http://en.wikipedia.org/wiki/$UserInput$"
DefaultSearch2Icon=#*@*#Images\Search\Wiki.#*ColorImage*#.png
DefaultSearch3=YouTube
DefaultSearch3Command="http://www.youtube.com/results?search_query=$UserInput$"
DefaultSearch3Icon=#*@*#Images\Search\YouTube.#*ColorImage*#.png
DefaultSearch4=Twitter
DefaultSearch4Command="https://twitter.com/#!/search/$UserInput$"
DefaultSearch4Icon=#*@*#Images\Search\Twitter.#*ColorImage*#.png
DefaultSearch5=Rainmeter.net
DefaultSearch5Command="https://www.google.com/search?q=site%3Ahttp%3A%2F%2Frainmeter.net%2Fcms%2F%20$UserInput$"
DefaultSearch5Icon=#*@*#Images\Search\Run.#*ColorImage*#.png