[MeasureMediaPlayer]
Measure=NowPlaying
PlayerName=#MusicPlayer#
PlayerType=FILE

[MeasureTrack]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=TITLE

[MeasureAlbum]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=ALBUM

[MeasureArtist]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=ARTIST

[MeasureCover]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=COVER

[MeasureTimeDuration]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=DURATION

[MeasureTimePosition]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=POSITION

[MeasureTimeProgress]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=PROGRESS

[MeasureState]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=STATE

[MeasureRepeat]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=REPEAT

[MeasureShuffle]
Measure=NowPlaying
PlayerName=[MeasureMediaPlayer]
PlayerType=SHUFFLE