;--------------------------------------------------------------------------------------------
; SIDEBAR

[Rainmeter]
Group=EnigmaSidebar
Blur=1
MiddleMouseUpAction=!Refresh

;---------------------------------------------------------------------
; SIDEBAR (1)

[StyleSidebar]
ImageName=#SidebarImage#
W=#SidebarWidth#
H=(#WORKAREAHEIGHT# - #SidebarSpacing#)
ImageAlpha=#SidebarAlpha#

;---------------------------------------------------------------------
; SIDEBAR (2)

[StyleSidebar2]
ImageName=#SecondSidebarImage#
W=#SidebarWidth#
H=(#WORKAREAHEIGHT# - #SidebarSpacing#)
ImageAlpha=#SidebarAlpha#