[Variables]

;-----------------------
; LAYOUT

Stylesheet=Enigma Dark

;-----------------------
; GENERAL

Note1Path=#SKINSPATH#Enigma\Sidebar\Notes\Notes.txt
Note2Path=#SKINSPATH#Enigma\Sidebar\Notes\Tasks.txt
Note3Path=#SKINSPATH#Enigma\Sidebar\Notes\About.txt
NoteHeight=200
Drive1=C
Drive2=E
Drive3=F
NetworkMaxDownload=1000000
NetworkMaxUpload=500000
CalendarExtraDays=1
CalendarLeadingZeroes=0
CalendarMondays=0
GalleryPath=%USERPROFILE%\Pictures
GallerySubfolders=1
GalleryRatio=3/4
VolumeIncrement=5
TriptychInterval=30
TriptychDisabled=0

;-----------------------
; MUSIC

MusicPlayerType=3
MusicPlayer=iTunes

;-----------------------
; FEEDS

Feed1=http://news.google.com/news?pz=1&ned=us&hl=en&topic=h&num=10&output=rss
Feed2=http://rainmeter.net/forum/feed.php
Feed3=http://kaelri.com/feed/
GmailUsername=YourUsernameHere
GmailPassword=YourPasswordHere
TwitterUsername=YourUsernameHere
TwitterPassword=YourPasswordHere
FacebookFeed=YourFacebookFeedHere
GoogleCalendar1=YourCalendarAddressHere
GoogleCalendar2=YourCalendarAddressHere
GoogleCalendar3=YourCalendarAddressHere
RTMusername=YourUserNameHere
RTMpassword=YourPasswordHere
RTMlist1=YourListNumberHere
RTMlist2=YourListNumberHere
RTMlist3=YourListNumberHere

;-----------------------
; WORLD

WeatherCode=YourWeatherCodeHere
UnitType=1
Unit=c
World1WeatherCode=UKXX0085
World1DSTOffset=-1
World2WeatherCode=IRXX0018
World2DSTOffset=-0.5
World3WeatherCode=ISXX0010
World3DSTOffset=-1

;-----------------------
; APPS

App1=Chrome
App1Path=chrome.exe
App1Label=WEB
App1Icon=#@#Images\Launcher\Chrome.#ColorImage#.png
App2=Notepad
App2Path=notepad.exe
App2Label=TEXT
App2Icon=#@#Images\Launcher\Text.#ColorImage#.png
App3=Explorer
App3Path=explorer.exe
App3Label=FILES
App3Icon=#@#Images\Launcher\Start.#ColorImage#.png
App4=Skype
App4Path=C:\Program Files\Skype\Phone\skype.exe
App4Label=CHAT
App4Icon=#@#Images\Launcher\Skype.#ColorImage#.png
App5=Rainmeter.net
App5Path=http://rainmeter.net/
App5Label=FORUM
App5Icon=#@#Images\Launcher\Rainmeter.png

;-----------------------
; SEARCH

Search1=Google
Search1Command="http://google.com/search?q=$UserInput$"
Search1Icon=#@#Images\Search\Google.#ColorImage#.png
Search2=Wikipedia
Search2Command="http://en.wikipedia.org/wiki/$UserInput$"
Search2Icon=#@#Images\Search\Wiki.#ColorImage#.png
Search3=YouTube
Search3Command="http://www.youtube.com/results?search_query=$UserInput$"
Search3Icon=#@#Images\Search\YouTube.#ColorImage#.png
Search4=Twitter
Search4Command="https://twitter.com/#!/search/$UserInput$"
Search4Icon=#@#Images\Search\Twitter.#ColorImage#.png
Search5=Run
Search5Command=$UserInput$
Search5Icon=#@#Images\Search\Run.#ColorImage#.png
