;--------------------------------------------------------------------------------------------
; ENIGMA LIGHT

[Variables]
Color1=0,0,0
Color2=#Color1#,160
Color3=#Color1#,108
Color4=#Color1#,25
ColorLink=64,96,128
ColorLink2=#ColorLink#,217
ColorLink3=#ColorLink#,160
ColorBorder=64,64,64
ColorBorder2=#ColorBorder#, 128
ColorBorder3=#ColorBorder#, 92
ColorBorder4=#ColorBorder#, 64
ColorPanel=231,231,231
ColorPanel2=#ColorPanel#,128
ColorFilter=255,255,255
ColorFilter2=#ColorFilter#,192
ColorFilter3=#ColorFilter#,128
ColorTransparent=0,0,0,2
ColorImageType=2
ColorImage=B

Size1=10
Size4=7
Size3=8
Size2=9
Font=Trebuchet MS
HideBordersTop=0
HideBordersBottom=1

SidebarWidth=200
SidebarSpacing=44
SidebarAlpha=128
SidebarImage=#@#Images\Sidebar\Sidebar.#ColorImage#.jpg
SecondSidebarImage=#@#Images\Sidebar\Sidebar.#ColorImage#.jpg

TaskbarHeight=44
TaskbarSpacing=0
TaskbarAlpha=204
TaskbarImage=#@#Images\Taskbar\Taskbar.#ColorImage#.jpg
SecondTaskbarImage=#@#Images\Taskbar\Taskbar.#ColorImage#.jpg

SidebarClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
SidebarWorldClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
TaskbarClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
