;--------------------------------------------------------------------------------------------
; ENIGMA DARK
; These are the default user setting values for the Enigma Dark stylesheet. They are used by the Options skin to restore default values.
; You should not make changes to this file unless you know what you're doing. Instead, use Enigma Dark.inc to change your active personal settings.

[Variables]
DefaultColor1=0,0,0
DefaultColor2=#Color1#,160
DefaultColor3=#Color1#,108
DefaultColor4=#Color1#,25
DefaultColorLink=64,96,128
DefaultColorLink2=#ColorLink#,217
DefaultColorLink3=#ColorLink#,160
DefaultColorBorder=64,64,64
DefaultColorBorder2=#ColorBorder#, 128
DefaultColorBorder3=#ColorBorder#, 92
DefaultColorBorder4=#ColorBorder#, 64
DefaultColorPanel=231,231,231
DefaultColorPanel2=#ColorPanel#,128
DefaultColorFilter=255,255,255
DefaultColorFilter2=#ColorFilter#,192
DefaultColorFilter3=#ColorFilter#,128
DefaultColorTransparent=0,0,0,2
DefaultColorImageType=2
DefaultColorImage=B

DefaultSize1=10
DefaultSize4=7
DefaultSize3=8
DefaultSize2=9
DefaultFont=Trebuchet MS
DefaultHideBordersTop=0
DefaultHideBordersBottom=1

DefaultSidebarWidth=200
DefaultSidebarSpacing=44
DefaultSidebarAlpha=128
DefaultSidebarImage=#@#Images\Sidebar\Sidebar.#ColorImage#.jpg
DefaultSecondSidebarImage=#@#Images\Sidebar\Sidebar.#ColorImage#.jpg

DefaultTaskbarHeight=44
DefaultTaskbarSpacing=0
DefaultTaskbarAlpha=204
DefaultTaskbarImage=#@#Images\Taskbar\Taskbar.#ColorImage#.jpg
DefaultSecondTaskbarImage=#@#Images\Taskbar\Taskbar.#ColorImage#.jpg

DefaultSidebarClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
DefaultSidebarWorldClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
DefaultTaskbarClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png