;---------------------------------------------------------------------
; METERS

[Background]
Meter=Image
MeterStyle=Style#Variant#Background

[Icon]
Meter=Image
MeterStyle=Style#Variant#Icon | StyleLocationIcon

[Text]
Meter=STRING
MeterStyle=Style#Variant#Text
MeasureName=MeasureWeatherCity

[Label]
Meter=STRING
MeterStyle=Style#Variant#Label
MeasureName=MeasureWeatherLatitude
MeasureName2=MeasureWeatherLongitude
Text=%1, %2