;--------------------------------------------------------------------------------------------
; ENIGMA LIGHT
; These are the default user setting values for the Enigma Light stylesheet. They are used by the Options skin to restore default values.
; You should not make changes to this file unless you know what you're doing. Instead, use Options.inc to change your active personal settings.

[Variables]
DefaultColor1=30,30,30
DefaultColor2=95,95,95
DefaultColor3=147,147,147
DefaultColor4=230,230,230
DefaultColorLink=64,96,128
DefaultColorLink2=#*ColorLink*#,217
DefaultColorLink3=#*ColorLink*#,160
DefaultColorBorder=64,64,64
DefaultColorBorder2=#*ColorBorder*#,128
DefaultColorBorder3=#*ColorBorder*#,92
DefaultColorBorder4=#*ColorBorder*#,64
DefaultColorPanel=231,231,231
DefaultColorPanel2=#*ColorPanel*#,128
DefaultColorFilter=255,255,255
DefaultColorFilter2=#*ColorFilter*#,192
DefaultColorFilter3=#*ColorFilter*#,128
DefaultColorEvent=255,0,0
DefaultColorEvent2=#*ColorEvent*#,92
DefaultColorTransparent=0,0,0,2
DefaultColorImage=B

DefaultSize1=10
DefaultSize4=7
DefaultSize3=8
DefaultSize2=9
DefaultFont=Trebuchet MS
DefaultSkinBackgroundAlpha=100
DefaultHideBordersTop=1
DefaultHideBordersBottom=1

DefaultSidebarWidth=200
DefaultSidebarSpacingFixed=1
DefaultSidebarAlpha=255
DefaultSidebarImage=#*@*#Images\Sidebar\SidebarLeft.#*ColorImage*#.jpg
DefaultSecondSidebarImage=#*@*#Images\Sidebar\SidebarRight.#*ColorImage*#.jpg

DefaultTaskbarHeight=44
DefaultTaskbarSpacingFixed=0
DefaultTaskbarAlpha=204
DefaultTaskbarImage=#*@*#Images\Taskbar\TaskbarTop.#*ColorImage*#.jpg
DefaultSecondTaskbarImage=#*@*#Images\Taskbar\TaskbarBottom.#*ColorImage*#.jpg
DefaultTaskbarMaxSkinWidth=200
DefaultTaskbarMinSkinWidth=60
DefaultTaskbarHideTriptych=1

DefaultSidebarClockFace=#*@*#Images\Clock\ChevronClock.#*ColorImage*#.png
DefaultSidebarWorldClockFace=#*@*#Images\Clock\ChevronClock.#*ColorImage*#.png
DefaultTaskbarClockFace=#*@*#Images\Clock\ChevronClock.#*ColorImage*#.png