;--------------------------------------------------------------------------------------------
; ENIGMA LIGHT

[Variables]
Color1=30,30,30
Color2=95,95,95
Color3=147,147,147
Color4=230,230,230
ColorLink=64,96,128
ColorLink2=#ColorLink#,217
ColorLink3=#ColorLink#,160
ColorBorder=64,64,64
ColorBorder2=#ColorBorder#,128
ColorBorder3=#ColorBorder#,92
ColorBorder4=#ColorBorder#,64
ColorPanel=231,231,231
ColorPanel2=#ColorPanel#,128
ColorFilter=255,255,255
ColorFilter2=#ColorFilter#,192
ColorFilter3=#ColorFilter#,128
ColorEvent=255,0,0
ColorEvent2=#ColorEvent#,92
ColorTransparent=0,0,0,2
ColorImage=B

Size1=10
Size4=7
Size3=8
Size2=9
Font=Trebuchet MS
SkinBackgroundAlpha=100
HideBordersTop=1
HideBordersBottom=1

SidebarWidth=200
SidebarSpacingFixed=1
SidebarAlpha=255
SidebarImage=#@#Images\Sidebar\SidebarLeft.#ColorImage#.jpg
SecondSidebarImage=#@#Images\Sidebar\SidebarRight.#ColorImage#.jpg

TaskbarHeight=44
TaskbarSpacingFixed=0
TaskbarAlpha=204
TaskbarImage=#@#Images\Taskbar\TaskbarTop.#ColorImage#.jpg
SecondTaskbarImage=#@#Images\Taskbar\TaskbarBottom.#ColorImage#.jpg
TaskbarMaxSkinWidth=200
TaskbarMinSkinWidth=60
TaskbarHideTriptych=1

SidebarClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
SidebarWorldClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
TaskbarClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png